unique_ids:
  assets:
    standard-page.html: DCIKSLIDNVUQ7NVV3VYUUIMLTI7BDO4N
    theme.css: IEDL5LE5IODP43PMHUJJ46SNA7U572T3
  forms:
    BookingModal: CV7X35LPOCISVHKZ54M2VRW2GVPM6WRD
    BookingModal.ItemTemplate2: GYW3HCIJIHVO7ILKRWTTNKYM4AIB2O32
    Homepage: Z5SLA26VHRYSP3BUK7NOYISRUF47K6OJ
    Homepage.ItemTemplate1: WCNJVBMZXDVSTMKEJBCAE4QLKRRX4HNA
    RoomPlanModal: 7G2QEMUFDFXN4Z4Y6TQYBJKGO45M5N7Y
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: 636ST42P7OU2TXYT6F727EDJBWOX2XAU
